# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1101, 480)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.deleteSelectedButton = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteSelectedButton.sizePolicy().hasHeightForWidth())
        self.deleteSelectedButton.setSizePolicy(sizePolicy)
        self.deleteSelectedButton.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteSelectedButton.setFont(font)
        self.deleteSelectedButton.setObjectName("deleteSelectedButton")
        self.horizontalLayout_2.addWidget(self.deleteSelectedButton)
        self.backButton = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        self.backButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_2.addWidget(self.backButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.historyName = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.historyName.setFont(font)
        self.historyName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.historyName.setObjectName("historyName")
        self.gridLayout.addWidget(self.historyName, 0, 0, 1, 1)
        self.historyTable = QtWidgets.QTableWidget(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.historyTable.setFont(font)
        self.historyTable.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.historyTable.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.historyTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.AnyKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed)
        self.historyTable.setAlternatingRowColors(False)
        self.historyTable.setWordWrap(True)
        self.historyTable.setCornerButtonEnabled(True)
        self.historyTable.setObjectName("historyTable")
        self.historyTable.setColumnCount(0)
        self.historyTable.setRowCount(0)
        self.gridLayout.addWidget(self.historyTable, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.deleteSelectedButton.setText(_translate("Form", "Удалить выбранное"))
        self.backButton.setText(_translate("Form", "Назад"))
        self.historyName.setText(_translate("Form", "История ..."))
